# Generated by Django 3.0.11 on 2021-01-15 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('startDate', models.DateField(default=django.utils.timezone.now)),
                ('endDate', models.DateField()),
                ('length', models.IntegerField()),
                ('warrantyNumber', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=100)),
                ('serialNumber', models.CharField(max_length=50)),
            ],
        ),
    ]
