# Generated by Django 3.0.11 on 2021-01-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='phoneNumber',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
