# Generated by Django 2.1.15 on 2021-05-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='serialNumber',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
